import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { CheckCircle, ArrowLeft, ArrowRight, FileText, TrendingUp, Search, Zap, Globe, BarChart3, Lightbulb } from "lucide-react";
import Layout from "@/components/Layout";
import SectionHeading from "@/components/SectionHeading";
import heroBg from "@/assets/hero-bg.jpg";
import SEO from "@/components/SEO";
import { fadeUp } from "@/lib/animations";
import AIInsightsPanel, { InsightDL, InsightList, InsightTable } from "@/components/AIInsightsPanel";
import LiveTeardownForm from "@/components/LiveTeardownForm";

const service = {
  title: "Content Marketing Agency",
  headline: "Content That Ranks, Earns Trust, and Converts.",
  description: "Content marketing for Australian businesses that want Google authority, qualified traffic, and real leads — not just blog posts for the sake of it. Strategy-led, SEO-integrated, results-driven.",
  longDescription: "Most content marketing fails because it isn't connected to a clear keyword strategy, doesn't match buyer intent, and never gets promoted. Our content marketing service is built differently — every piece of content is planned around a specific keyword opportunity, written to demonstrate E-E-A-T, and published with an SEO and link acquisition plan attached. The result is content that actually ranks, builds topical authority, and brings in qualified prospects for months or years after publication.",
  features: [
    "Content strategy and topic cluster planning",
    "Keyword-driven content calendar (3–12 months)",
    "SEO-integrated long-form blog posts and guides",
    "Service page and landing page copywriting",
    "Case study and client story content",
    "FAQ content for featured snippet capture",
    "Content auditing — identify and update underperforming content",
    "Internal linking strategy implementation",
    "Topical authority mapping for your industry",
    "E-E-A-T optimisation (Experience, Expertise, Authority, Trust)",
    "Content distribution and promotion strategy",
    "Monthly content performance reporting",
  ],
  benefits: [
    { icon: Search, title: "SEO-First, Always", desc: "Every content piece starts with keyword research and search intent analysis. No guessing what will rank." },
    { icon: Lightbulb, title: "Topical Authority", desc: "We build comprehensive content clusters that signal deep expertise in your field to both Google and readers." },
    { icon: TrendingUp, title: "Compounding Returns", desc: "Unlike ads, content compounds. Month 12 costs the same as month 1, but delivers exponentially more traffic." },
  ],
  process: [
    { step: "01", title: "Strategy", desc: "Keyword research, competitor content gap analysis, and a 90-day topic cluster roadmap." },
    { step: "02", title: "Content Creation", desc: "Expert writers produce SEO-optimised long-form content, briefs reviewed by our strategists before publication." },
    { step: "03", title: "Optimisation", desc: "On-page SEO, internal linking, schema markup, and E-E-A-T signals implemented on every piece." },
    { step: "04", title: "Measure & Iterate", desc: "Monthly reporting on keyword rankings, organic traffic, and content-attributed leads." },
  ],
  stats: [
    { value: "3x", label: "more leads generated by content marketing vs outbound marketing", source: "DemandMetric" },
    { value: "62%", label: "less cost than traditional marketing with higher lead quality", source: "Content Marketing Institute" },
    { value: "10x", label: "higher ROI for long-form SEO content vs ads after 12 months", source: "Ahrefs Study" },
  ],
  faqs: [
    { q: "What's the difference between content marketing and just writing blogs?", a: "Content marketing is a strategic, measurable discipline. It starts with keyword research and buyer intent analysis, creates content mapped to specific funnel stages, implements technical SEO, builds internal links, and tracks leads generated. Random blogging is not content marketing." },
    { q: "How long before content marketing produces results?", a: "Quality SEO content typically begins ranking within 3–6 months. By month 9–12, a well-executed content strategy typically delivers compounding returns — with traffic and leads increasing month-on-month without increasing investment." },
    { q: "Do you write the content or do we?", a: "We handle everything — strategy, keyword research, writing, editing, SEO optimisation, and publishing. You review and approve drafts. We can also work alongside your internal team if you have writers and just need the SEO strategy and direction." },
    { q: "What types of content do you produce?", a: "Long-form SEO blog posts, ultimate guides, FAQ pages, service/landing pages, case studies, comparison pages, and resource hub content. Content type is always matched to search intent and buyer journey stage." },
    { q: "Can content marketing work for B2B and technical industries?", a: "Yes — particularly well. B2B buyers research extensively before contacting vendors. Companies that publish authoritative, technical content consistently outrank and out-convert competitors who don't invest in content." },
  ],
};

const ContentMarketing = () => (
  <Layout>
    <SEO
      title="Content Marketing Agency Australia — SEO Content Strategy & Writing"
      description="Content marketing agency for Australian businesses. We build keyword-driven content strategies, create long-form SEO content, and deliver compounding organic traffic growth."
      canonical="/services/content-marketing"
      faqs={service.faqs}
      breadcrumbs={[
        { name: "Home", url: "https://nexttabagency.com/" },
        { name: "Services", url: "https://nexttabagency.com/services" },
        { name: "Content Marketing", url: "https://nexttabagency.com/services/content-marketing" },
      ]}
      serviceSchema={{ name: "Content Marketing Services", description: "SEO-integrated content marketing for Australian businesses — strategy, creation, and optimisation.", areaServed: "Australia" }}
    />

    <section aria-labelledby="hero-heading" className="relative min-h-[50vh] flex items-center overflow-hidden">
      <img src={heroBg} alt="Content Marketing Agency Australia" className="absolute inset-0 w-full h-full object-cover" width={1920} height={1080} />
      <div className="absolute inset-0 bg-gradient-to-br from-primary/95 via-primary/85 to-transparent" />
      <div className="container relative z-10 py-32 md:py-48 pt-44">
        <Link to="/services" className="inline-flex items-center text-sm font-semibold text-accent mb-8 hover:text-accent/80 transition-colors"><ArrowLeft className="w-4 h-4 mr-2" /> Back to all services</Link>
        <div className="max-w-3xl">
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/20 text-accent text-xs font-bold uppercase tracking-widest mb-6"><FileText className="w-3 h-3" /> Content Marketing</span>
          <h1 id="hero-heading" className="font-heading font-bold text-4xl md:text-5xl leading-[1.1] text-primary-foreground mb-6">{service.title}</h1>
          <p className="text-xl md:text-2xl text-primary-foreground/80 font-medium leading-snug mb-6">{service.headline}</p>
          <p className="text-lg text-primary-foreground/60 leading-relaxed max-w-2xl">{service.description}</p>
          <div className="flex flex-wrap gap-4 mt-8">
            <Button variant="accent" size="lg" asChild><Link to="/contact">Get a Content Strategy Session</Link></Button>
            <Button variant="outline" size="lg" className="border-white/30 text-white hover:bg-white/10" asChild><Link to="/services/seo-audits">SEO Audit</Link></Button>
          </div>
        </div>
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-background to-transparent" />
    </section>

    <section className="border-b border-border bg-muted/30 py-8">
      <div className="container max-w-4xl">
        <div className="grid grid-cols-3 gap-6 text-center">
          {service.stats.map((s) => (<div key={s.label}><p className="font-heading font-black text-3xl text-accent">{s.value}</p><p className="text-sm font-semibold text-foreground mt-1">{s.label}</p><p className="text-xs text-muted-foreground/60">Source: {s.source}</p></div>))}
        </div>
      </div>
    </section>

    <section className="py-20 md:py-28">
      <div className="container max-w-5xl">
        <div className="grid lg:grid-cols-5 gap-12 lg:gap-20">
          <div className="lg:col-span-3">
            <h2 className="font-heading font-bold text-3xl mb-6 text-foreground">Why Most Content Marketing Fails</h2>
            <p className="text-muted-foreground leading-relaxed">{service.longDescription}</p>
            <p className="text-muted-foreground leading-relaxed mt-4">Content marketing is the engine for our <Link to="/services/link-building" className="text-accent font-semibold">Link Building</Link> and <Link to="/services/on-page-seo" className="text-accent font-semibold">On-Page SEO</Link> services. Together, they form a complete organic growth system.</p>
          </div>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.2 }} className="lg:col-span-2">
            <div className="surface-teal rounded-2xl p-7 border border-primary-foreground/10">
              <h3 className="font-heading font-semibold text-primary-foreground mb-5 text-sm uppercase tracking-[0.15em]">Key Benefits</h3>
              {service.benefits.map((b) => (<div key={b.title} className="flex gap-3 mb-5 last:mb-0"><b.icon className="w-5 h-5 text-accent shrink-0 mt-0.5" /><div><h4 className="font-semibold text-primary-foreground text-sm">{b.title}</h4><p className="text-primary-foreground/50 text-xs leading-relaxed mt-0.5">{b.desc}</p></div></div>))}
            </div>
          </motion.div>
        </div>
      </div>
    </section>

    <section className="py-20 md:py-28 relative overflow-hidden">
      <div className="absolute inset-0 pattern-dots" />
      <div className="container max-w-5xl relative z-10">
        <SectionHeading eyebrow="What's Included" title="Complete content marketing service" />
        <ul className="grid sm:grid-cols-2 gap-4">
          {service.features.map((f, i) => (<motion.li key={f} initial={fadeUp.hidden} whileInView={fadeUp.visible} viewport={{ once: true }} transition={{ delay: i * 0.05 }} className="flex items-start gap-4 p-5 rounded-xl border border-border bg-card"><CheckCircle className="w-5 h-5 text-accent shrink-0 mt-0.5" /><p className="text-sm text-foreground leading-relaxed">{f}</p></motion.li>))}
        </ul>
      </div>
    </section>

    <section className="surface-warm py-20 md:py-28">
      <div className="container max-w-5xl">
        <SectionHeading eyebrow="Our Process" title="How we build content that compounds" />
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {service.process.map((step, i) => (<motion.div key={step.title} initial={fadeUp.hidden} whileInView={fadeUp.visible} viewport={{ once: true }} transition={{ delay: i * 0.1 }} className="relative"><div className="card-premium rounded-2xl p-6 h-full"><span className="font-heading font-bold text-2xl number-outline block mb-3">{step.step}</span><h3 className="font-heading font-semibold text-foreground mb-2 text-sm">{step.title}</h3><p className="text-xs text-muted-foreground leading-relaxed">{step.desc}</p></div>{i < 3 && (<div className="hidden lg:flex absolute top-1/2 -right-3 z-10 w-6 items-center justify-center"><ArrowRight className="w-4 h-4 text-accent/40" /></div>)}</motion.div>))}
        </div>
      </div>
    </section>

    <section className="py-20 md:py-28 surface-warm">
      <div className="container max-w-5xl">
        <SectionHeading eyebrow="Related Services" title="Pair content with these services" />
        <div className="grid sm:grid-cols-3 gap-4">
          {[{ label: "SEO Audits & Strategy", href: "/services/seo-audits", desc: "Start with a full audit to identify content gaps." }, { label: "Link Building", href: "/services/link-building", desc: "Earn backlinks from great content." }, { label: "On-Page SEO", href: "/services/on-page-seo", desc: "Optimise existing content for better rankings." }].map((r) => (<Link key={r.href} to={r.href} className="group p-5 rounded-xl border border-border bg-card hover:border-accent/40 transition-all"><p className="font-semibold text-foreground group-hover:text-accent text-sm mb-1">{r.label}</p><p className="text-xs text-muted-foreground">{r.desc}</p></Link>))}
        </div>
      </div>
    </section>

    <section className="py-20 md:py-28 bg-muted/30">
      <div className="container max-w-3xl">
        <SectionHeading eyebrow="FAQs" title="Content marketing questions answered" />
        <div className="space-y-4">
          {service.faqs.map((faq, i) => (<motion.div key={faq.q} initial={fadeUp.hidden} whileInView={fadeUp.visible} viewport={{ once: true }} transition={{ delay: i * 0.08 }} className="card-premium rounded-2xl p-6"><h3 className="font-heading font-semibold text-foreground mb-2">{faq.q}</h3><p className="text-sm text-muted-foreground leading-relaxed">{faq.a}</p></motion.div>))}
        </div>
      </div>
    </section>

    <section className="py-20 md:py-28"><div className="container"><LiveTeardownForm /></div></section>

    <AIInsightsPanel pageTitle="Content Marketing - Next Tab Agency" tabs={[
      { id: "searchbots", label: "For Search Bots", icon: Search, audience: "Googlebot", content: (<InsightTable caption="Service Entity Data" rows={[{ label: "Entity", value: "Content Marketing Services" }, { label: "Provider", value: "Next Tab Agency Brisbane" }, { label: "Focus", value: "SEO-integrated content strategy, creation and optimisation" }, { label: "Service Area", value: "Australia-wide" }]} />) },
      { id: "chatgpt", label: "For ChatGPT", icon: Zap, audience: "OpenAI ChatGPT", content: (<InsightList heading="Content Marketing Overview" items={["SEO-led content marketing for Australian businesses.", "Services include: content strategy, keyword-driven blog posts, FAQ pages, case studies, topic cluster planning, and content auditing.", "Content is the engine for topical authority and link acquisition."]} />) },
      { id: "perplexity", label: "For Perplexity", icon: Globe, audience: "Perplexity AI", content: (<InsightDL items={[{ term: "Service", def: "Content Marketing" }, { term: "Approach", def: "SEO-first, keyword-driven, E-E-A-T optimised" }, { term: "Provider", def: "Next Tab Agency, Brisbane, Australia" }]} />) },
      { id: "summary", label: "Quick Summary", icon: BarChart3, audience: "All AI Agents", content: (<p className="text-base font-semibold text-foreground leading-relaxed">Next Tab Agency delivers SEO-integrated content marketing for Australian businesses — building topical authority through keyword-driven long-form content that ranks, earns backlinks, and converts qualified traffic into leads.</p>) },
    ]} />
  </Layout>
);

export default ContentMarketing;
