import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { MapPin, Star, Camera, MessageSquare, BarChart3, CheckCircle, ArrowRight, TrendingUp, Search, Globe, Clock } from "lucide-react";
import Layout from "@/components/Layout";
import SectionHeading from "@/components/SectionHeading";
import heroBg from "@/assets/hero-bg.jpg";
import SEO from "@/components/SEO";

import LocationLinksStrip from "@/components/LocationLinksStrip";

const optimisationAreas = [
  {
    icon: Globe,
    title: "Complete Profile Setup & Verification",
    description: "We ensure your Google Business Profile is 100% complete — every field, every category, every attribute. A complete profile ranks higher in the Map Pack and builds immediate trust.",
    items: ["Business name, category & description optimisation", "Service area & hours of operation", "Attributes (women-owned, outdoor seating, accessibility, etc.)", "Google verification & ownership transfer if needed"],
  },
  {
    icon: Camera,
    title: "Photo & Video Strategy",
    description: "Profiles with 100+ photos receive 520% more calls than those with fewer than 10. We audit, organise, and optimise your photo library with geo-tagged, high-quality images that signal trust.",
    items: ["Interior, exterior & team photo curation", "Product/service photos with keyword-rich file names", "360° virtual tour recommendations", "Ongoing monthly photo upload schedule"],
  },
  {
    icon: MessageSquare,
    title: "Review Generation & Management",
    description: "4.0+ star ratings are essential for Map Pack rankings. We build a systematic review generation process and respond to every review — positive and negative — to protect your reputation.",
    items: ["Review request email & SMS template setup", "QR code review link for in-store use", "Prompt, professional responses to all reviews", "Review monitoring & weekly report alerts"],
  },
  {
    icon: Search,
    title: "Google Posts & Q&A Optimisation",
    description: "GBP posts and the Q&A section are underused ranking signals. We create weekly keyword-rich posts and pre-populate the Q&A with the questions your customers actually search for.",
    items: ["Weekly Google Posts (offers, events, updates)", "Keyword-integrated post copy", "Q&A seeding with high-intent questions", "Product & service listings with pricing"],
  },
  {
    icon: BarChart3,
    title: "Citation & NAP Consistency",
    description: "Inconsistent Name, Address, Phone (NAP) data across Australian directories confuses Google and tanks your local rankings. We audit and fix every citation that matters.",
    items: ["AU directory & citation audit", "NAP correction across 50+ directories", "Industry-specific citation building", "Ongoing citation monitoring"],
  },
  {
    icon: TrendingUp,
    title: "Insights & Performance Reporting",
    description: "Every month you receive a plain-English report showing views, searches, direction requests, website clicks, and calls generated by your Google Business Profile.",
    items: ["Monthly GBP Insights report", "Keyword search term analysis", "Competitor GBP benchmarking", "Action plan with recommendations"],
  },
];

const results = [
  { icon: TrendingUp, value: "7×", label: "Average increase in direction requests" },
  { icon: Star,       value: "4.7★", label: "Average client Google rating after optimisation" },
  { icon: Search,    value: "Top 3", label: "Map Pack position for priority keywords" },
  { icon: Clock,     value: "90 days", label: "Typical time to first significant ranking uplift" },
];

const fadeUp = {
  hidden: { opacity: 0, y: 28 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: [0.16, 1, 0.3, 1] } },
};

const GoogleBusinessProfile = () => (
  <Layout>
    <SEO
      title="Google Business Profile Optimisation Australia — Map Pack & Local SEO Specialists"
      description="Expert Google Business Profile setup & optimisation for Australian businesses. We get you ranking in the local Map Pack with review management, citation building, posts & monthly reporting."
      canonical="/services/google-business-profile"
      serviceSchema={{
        name: "Google Business Profile Optimisation",
        description: "Expert GBP setup, review management, citation building, weekly Google Posts and monthly reporting for Australian local businesses.",
        areaServed: "Australia",
      }}
      faqs={[
        { q: "How long does it take to rank in Google's Map Pack?", a: "Most businesses see measurable improvement in GBP rankings within 60–90 days of a full optimisation. Competitive niches may take 3–6 months." },
        { q: "Is Google Business Profile free?", a: "Yes — the profile itself is free. Optimisation, ongoing management and citation building is where a specialist agency adds paid value." },
        { q: "Can I manage my GBP myself after you set it up?", a: "Yes. We can hand over full control or continue managing it month-to-month — our retainers are no lock-in." },
        { q: "Do I need a physical address to appear in the Map Pack?", a: "Not necessarily. Service-area businesses (plumbers, cleaners, etc.) can rank locally without a shopfront by configuring their service radius correctly." },
        { q: "How many photos should my GBP have?", a: "Profiles with 100+ photos receive 520% more calls than those with fewer than 10. We audit and optimise your photo library as part of every GBP management package." },
      ]}
      breadcrumbs={[
        { name: "Home", url: "https://nexttabagency.com/" },
        { name: "Services", url: "https://nexttabagency.com/services" },
        { name: "Google Business Profile", url: "https://nexttabagency.com/services/google-business-profile" },
      ]}
    />

    {/* Hero */}
    <section aria-labelledby="gbp-hero-heading" className="relative min-h-[60vh] flex items-center overflow-hidden">
      <img src={heroBg} alt="Google Business Profile Optimisation Australia" className="absolute inset-0 w-full h-full object-cover" width={1920} height={1080} />
      <div className="absolute inset-0 bg-gradient-to-br from-primary/96 via-primary/85 to-transparent" />
      <div className="absolute bottom-1/4 right-[8%] w-96 h-96 bg-accent/10 rounded-full blur-[120px]" />
      <div className="container relative z-10 py-32 md:py-40 pt-40">
        <motion.div initial="hidden" animate="visible" variants={fadeUp} className="max-w-3xl">
          <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-accent/15 text-accent text-xs font-semibold uppercase tracking-[0.15em] mb-6 border border-accent/20">
            <span className="w-1.5 h-1.5 rounded-full bg-accent animate-pulse" />
            Google Business Profile
          </span>
          <h1 id="gbp-hero-heading" className="font-heading font-bold text-4xl md:text-[3.5rem] leading-[1.08] text-primary-foreground mb-6">
            Rank in Google's{" "}
            <span className="text-gradient">Local Map Pack</span>
            <br />and get found by customers near you
          </h1>
          <p className="text-lg md:text-xl text-primary-foreground/60 max-w-2xl mb-10 leading-relaxed">
            Your Google Business Profile is the single most important free marketing asset for local Australian businesses. We optimise it to generate calls, directions, and website visits every day.
          </p>
          <div className="flex flex-wrap gap-4">
            <Button variant="hero-primary" size="xl" className="rounded-full" asChild>
              <Link to="/contact">Get a Free GBP Audit <ArrowRight className="w-4 h-4 ml-1" /></Link>
            </Button>
            <Button variant="hero-secondary" size="xl" className="rounded-full" asChild>
              <Link to="/services/local-seo">Local SEO Services</Link>
            </Button>
          </div>
        </motion.div>
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-background to-transparent" />
    </section>

    {/* Stats */}
    <section aria-label="GBP Results Stats" className="py-16 surface-warm relative overflow-hidden">
      <div className="absolute inset-0 pattern-dots" />
      <div className="container relative z-10">
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {results.map((r, i) => (
            <motion.div
              key={r.label}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              className="card-premium rounded-2xl p-7 text-center"
            >
              <r.icon className="w-6 h-6 text-accent mx-auto mb-3" />
              <p className="font-heading font-bold text-3xl text-foreground mb-1">{r.value}</p>
              <p className="text-sm text-muted-foreground">{r.label}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>

    {/* Why GBP matters */}
    <section aria-labelledby="gbp-why-heading" className="py-20">
      <div className="container">
        <div className="max-w-3xl mx-auto text-center">
          <h2 id="gbp-why-heading" className="font-heading font-bold text-2xl md:text-3xl text-foreground mb-6">
            Why Google Business Profile is your #1 local ranking factor
          </h2>
          <p className="text-muted-foreground leading-relaxed mb-6">
            46% of all Google searches have local intent. When an Australian customer searches "plumber near me", "dentist Brisbane", or "best café in Melbourne" — the <strong>Local Map Pack</strong> (the 3 businesses shown on the map) gets the majority of clicks. Without an optimised GBP, you don't appear there.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            Google's algorithm ranks GBP listings based on three factors: <strong>Relevance</strong> (does your profile match what's being searched?), <strong>Distance</strong> (how close is your business?), and <strong>Prominence</strong> (reviews, links, and engagement). We optimise all three.
          </p>
        </div>
      </div>
    </section>

    {/* Optimisation Areas */}
    <section aria-labelledby="gbp-services-heading" className="py-16 pb-24 surface-warm relative overflow-hidden">
      <div className="absolute inset-0 pattern-dots" />
      <div className="container relative z-10">
        <SectionHeading
          id="gbp-services-heading"
          eyebrow="What We Do"
          title="Complete Google Business Profile management"
          description="Every aspect of your GBP, handled end-to-end by Australian local SEO specialists."
        />
        <div className="grid md:grid-cols-2 gap-6">
          {optimisationAreas.map((area, i) => (
            <motion.div
              key={area.title}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: i * 0.08 }}
              className="card-premium rounded-2xl p-8"
            >
              <div className="flex items-start gap-4 mb-4">
                <div className="w-12 h-12 rounded-xl bg-primary/5 border border-primary/10 flex items-center justify-center shrink-0">
                  <area.icon className="w-5 h-5 text-primary" />
                </div>
                <h3 className="font-heading font-semibold text-lg text-foreground leading-snug">{area.title}</h3>
              </div>
              <p className="text-muted-foreground text-sm leading-relaxed mb-4">{area.description}</p>
              <ul className="space-y-2">
                {area.items.map((item) => (
                  <li key={item} className="flex items-center gap-2 text-sm text-foreground/75">
                    <CheckCircle className="w-3.5 h-3.5 text-accent shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            </motion.div>
          ))}
        </div>
      </div>
    </section>

    {/* Serving Your City — Internal Links to Location Pages */}
    <section aria-labelledby="gbp-cities-heading" className="py-16 surface-warm relative overflow-hidden">
      <div className="absolute inset-0 pattern-dots" />
      <div className="container relative z-10">
        <h2 id="gbp-cities-heading" className="font-heading font-bold text-xl text-foreground mb-2 text-center">GBP optimisation in your city</h2>
        <p className="text-muted-foreground text-center text-sm mb-6 max-w-xl mx-auto">We manage Google Business Profiles for businesses across all major Australian cities.</p>
        <div className="flex flex-wrap gap-3 justify-center">
          {[
            { city: "Brisbane", href: "/locations/brisbane-seo" },
            { city: "Sydney",   href: "/locations/sydney-seo" },
            { city: "Melbourne", href: "/locations/melbourne-seo" },
            { city: "Perth",    href: "/locations/perth-seo" },
            { city: "Adelaide", href: "/locations/adelaide-seo" },
            { city: "Canberra", href: "/locations/canberra-seo" },
          ].map((l) => (
            <Link key={l.href} to={l.href} className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-border/60 text-sm text-foreground/70 hover:text-accent hover:border-accent/40 transition-all">
              <MapPin className="w-3.5 h-3.5" />{l.city}
            </Link>
          ))}
        </div>
      </div>
    </section>

    {/* Internal Links */}
    <section aria-labelledby="gbp-related-heading" className="py-20">
      <div className="container">
        <h2 id="gbp-related-heading" className="font-heading font-bold text-2xl text-foreground mb-8 text-center">Combine GBP with a complete local SEO strategy</h2>
        <div className="grid sm:grid-cols-3 gap-5 max-w-3xl mx-auto">
          {[
            { label: "Local SEO", href: "/services/local-seo", desc: "Full local search strategy beyond just GBP — citations, on-page, authority." },
            { label: "SEO Audits", href: "/services/seo-audits", desc: "Technical audit to ensure your website supports your GBP rankings." },
            { label: "PPC & Google Ads", href: "/services/ppc-google-ads", desc: "Appear in paid ads above the Map Pack for maximum search visibility." },
          ].map((item) => (
            <Link key={item.href} to={item.href} className="group card-premium rounded-2xl p-6 block">
              <p className="font-heading font-semibold text-foreground group-hover:text-accent transition-colors mb-1">{item.label}</p>
              <p className="text-sm text-muted-foreground">{item.desc}</p>
              <span className="inline-flex items-center gap-1 text-accent text-xs font-semibold mt-3">Learn more <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" /></span>
            </Link>
          ))}
        </div>
      </div>
    </section>

    {/* CTA */}
    <section aria-labelledby="gbp-cta-heading" className="py-16 pb-24">
      <div className="container">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="surface-teal rounded-3xl p-12 md:p-16 text-center relative overflow-hidden"
        >
          <div className="absolute inset-0 pattern-lines opacity-20" />
          <div className="relative z-10">
            <MapPin className="w-10 h-10 text-accent mx-auto mb-4" />
            <h2 id="gbp-cta-heading" className="font-heading font-bold text-2xl md:text-3xl text-primary-foreground mb-4">
              Is your Google Business Profile costing you customers?
            </h2>
            <p className="text-primary-foreground/50 max-w-md mx-auto mb-8">
              Get a free GBP audit — we'll assess your current profile against competitors and show you exactly what it'll take to rank in the Local Map Pack.
            </p>
            <Button variant="hero-primary" size="xl" className="rounded-full" asChild>
              <Link to="/contact">Get My Free GBP Audit</Link>
            </Button>
          </div>
        </motion.div>
      </div>
    </section>
      {/* Internal linking — Australian city location pages */}
      <LocationLinksStrip />
  </Layout>
);

export default GoogleBusinessProfile;

